apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: id-merger
  description: Matches between external ID (external feature ID) and OSM ID
  links:
  - url: https://mapcolonies.atlassian.net/wiki/spaces/MAPConflicResolution/pages/1353613504/Ingestion#Details-about-our-services
    title: Confluence 
    icon: article
  annotations:
    github.com/project-slug: MapColonies/id-merger
spec:
  type: service
  lifecycle: production
  owner: vector-team
  system: vector-ingestion
  providesApis:
    - id-merger-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: id-merger-api
  description: An API for for merging external OSM mapping with internal OSM mapping
spec:
  type: openapi
  lifecycle: production
  owner: vector-team
  system: vector-ingestion
  definition: |
    openapi: 3.0.1
    info:
      title: json-id-merger
      description: Merge external OSM mapping with internal OSM mapping
      version: 1.3.3
      license:
        name: MIT
        url: https://opensource.org/licenses/MIT
    paths:
      /merge:
        post:
          operationId: merger
          tags:
            - merge
          summary: merge external-tempId json and osmId-tempId json to external-tempId json
          requestBody:
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/MergedIdMapping'
          responses:
            '200':
              description: OK
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/MappingIdMergedResponse'
            '400':
              description: Bad Request
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/error'
            '422':
              description: Unprocessable Entity
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/error'
            '500':
              description: Internal Server Error
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/error'
    components:
      schemas:
        error:
          type: object
          required:
            - message
          properties:
            message:
              type: string
        MappingIdMergedResponse:
          type: array
          items:
            type: object
            properties:
              externalId:
                type: string
              osmId:
                type: number
        MergedIdMapping:
          type: object
          required:
            - externalMapping
            - osmMapping
          properties:
            externalMapping:
              type: array
              items:
                type: object
                properties:
                  tempOsmId:
                    type: number
                  externalId:
                    type: string
                additionalProperties: false
            osmMapping:
              type: array
              items:
                type: object
                properties:
                  tempOsmId:
                    type: number
                  osmId:
                    type: number
                additionalProperties: false
